%YAML 1.2
---
version: 1
formatters:
  base:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: base
    stream: ext://sys.stdout
  vc_info:
    class: logging.FileHandler
    level: INFO
    formatter: base
    filename: logging/view_controller_info.log
  vc_debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: base
    filename: logging/view_controller_debug.log
  model_info:
    class: logging.FileHandler
    level: INFO
    formatter: base
    filename: logging/model_info.log
  model_debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: base
    filename: logging/model_debug.log
loggers:
  view:
    level: DEBUG
    handlers: [console, vc_info, vc_debug]
    propagate: no
  controller:
    level: DEBUG
    handlers: [console, vc_info, vc_debug]
    propagate: no
  model:
    level: DEBUG
    handlers: [console, model_info, model_debug]
    propagate: no
