# Only one microscope can be active in the GUI at a time, but all microscopes will be accessible
microscopes:
  OPMv2:
    daq:
      hardware:
        type: NI

      # NI PCIe-1073 Chassis with PXI-6259 and PXI-6733 DAQ Boards.
      # Sampling rate in Hz
      sample_rate: 100000

      # triggers
      master_trigger_out_line: /Dev5/port0/line1
      camera_trigger_out_line: /Dev5/ctr0
      trigger_source: /Dev5/PFI0

    zoom:
      hardware:
        type: SyntheticZoom
        servo_id: 1
      position:
        1x: 0
      pixel_size:
        1x: 0.15
    shutter:
      hardware:
        type: SyntheticShutter
        channel: none/line0
    camera:
      hardware:
        name: camera
        type: HamamatsuOrca
        serial_number: 304064
      defect_correct_mode: 2.0
      delay: 7.5 #ms
      settle_down: 0.0 #ms
    remote_focus_device:
      hardware:
        type: NI
        channel: Dev5/ao3
        min: 0
        max: 5
      # Optotune EL-16-40-TC-VIS-5D-1-C
    galvo:
      # -
      #   name: xgalvo
      #   hardware:
      #     name: daq
      #     type: NI
      #     channel: Dev5/ao0
      #     min: -5
      #     max: 5
      #   frequency: 99.9
      #   amplitude: 2.5
      #   offset: 0
      #   duty_cycle: 50
      #   phase: 1.57079 # pi/2
      -
        name: ygalvo
        hardware:
          type: NI
          channel: Dev5/ao1
          min: -5
          max: 5
        phase: 1.57079 # pi/2
      -
        name: sheargalvo
        hardware:
          name: daq
          type: NI
          channel: Dev5/ao2
          min: -5
          max: 5
        phase: 1.57079 # pi/2
    stage:
      hardware:
        -
          name: fake_stage
          type: SyntheticStage
          serial_number: 123
          axes: [x,y,theta,f]
        -
          name: galvo-stage
          type: GalvoNIStage
          serial_number: 123
          axes: [z]
          axes_mapping: [Dev5/ao0]
          min: -5
          max: 5
          volts_per_micron: 0.01*x + 0

      x_max: 500
      x_min: -500
      y_max: 500
      y_min: -500
      z_max: 500
      z_min: -500
      f_max: 100000
      f_min: -100000
      theta_max: 360
      theta_min: 0

      x_offset: 0
      y_offset: 0
      z_offset: 0
      f_offset: 0
      theta_offset: 0
    filter_wheel:
      hardware:
        type: SyntheticFilterWheel
        wheel_number: 1
        port: COM6
        baudrate: 9600
      filter_wheel_delay: .030 # in seconds
      available_filters:
        FRFP - BLP01-664R-25: 0
        RFP - FF01-598/25-25: 1
        GFP - 527/20: 2
        GFPRFP - ZET488/561m: 3
        Empty-Alignment: 4
        Blocked2: 5
        Blocked3: 6
        Blocked4: 7
        Blocked5: 8
        Blocked6: 9
    lasers:
      # Omicron LightHub Ultra
      # 488 and 640 are LuxX+ Lasers
      # 561 is a Coherent OBIS Laser
      # Digital Laser Outputs
      - wavelength: 488
        power:
          hardware:
            type: NI
            channel: Dev5/ao12
            min: 0
            max: 5
        type: LuxX
      - wavelength: 562
        onoff:
          hardware:
            type: NI
            channel: Dev5/port1/line5
            min: 0
            max: 5
        power:
          hardware:
            type: NI
            channel: Dev5/ao13
            min: 0
            max: 5
        type: Obis
      - wavelength: 642
        power:
          hardware:
            type: NI
            channel: Dev5/ao14
            min: 0
            max: 5
        type: LuxX

gui:
  channels:
    count: 5
