# Specify all necessary information to find and connect to each hardware
# device that will be used on any of the scopes.
hardware:
  daq:
    type: NI #SyntheticDAQ or NI
  camera:
    -
      type: HamamatsuOrca
      serial_number: 000646

  filter_wheel:
    type: ASI #SyntheticFilterWheel or ASI
    port: COM13
    baudrate: 115200
    number_of_wheels: 1

  stage:
    -
      type: ASI
      port: COM13
      baudrate: 115200
      serial_number: 123456789
    -
      type: GalvoNIStage
      serial_number: 987654321
      timeout: 0.25
      baudrate: 9600
      stages: None
    -
      type: SyntheticStage
      serial_number: 123
      timeout: 0.25
      baudrate: 9600
      stages: None
  zoom:
    type: SyntheticZoom
    servo_id: 1
    port: COM18
    baudrate: 1000000

microscopes:
  OPM:
    daq:
      hardware:
        name: daq
        type: NI
      sample_rate: 100000
      sweep_time: 0.2
      master_trigger_out_line: PXI6723/port0/line1
      camera_trigger_out_line: /PXI6723/ctr0
      trigger_source: /PXI6723/PFI0
      laser_port_switcher: PXI6723/port0/line0
      laser_switch_state: False

    camera:
      hardware:
        name: camera
        type: HamamatsuOrca
        serial_number: 000646
      lightsheet_rolling_shutter_width: 608
      defect_correct_mode: 2.0
      delay_percent: 10
      pulse_percent: 1
      x_pixels_step: 4
      y_pixels_step: 4
      x_pixels_min: 4
      y_pixels_min: 4
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
      flip_x: False
      flip_y: False

    remote_focus_device:
      hardware:
        name: daq
        type: SyntheticRemoteFocus
        channel: PXI6723/ao2
        min: 0
        max: 5
      delay_percent: 7.5
      ramp_rising_percent: 85
      ramp_falling_percent: 2.5
      amplitude: 0.7
      offset: 2.3
      smoothing: 0.0

    galvo:
      -
        hardware:
          name: daq
          type: NI
          channel: PXI6723/ao0
          min: -10
          max: 10
        waveform: sine
        frequency: 99.9
        amplitude: 2.5
        offset: 0.5
        duty_cycle: 50
        phase: 1.57079

    filter_wheel:
      hardware:
        name: filter_wheel
        type: ASI
        wheel_number: 1
      filter_wheel_delay: .030
      available_filters:
        Empty-Alignment: 0
        GFP - FF01-515/30-32: 1
        RFP - FF01-595/31-32: 2
        Far-Red - BLP01-647R/31-32: 3
        Blocked1: 4
        Blocked2: 5
        Blocked3: 6
        Blocked4: 7
        Blocked5: 8
        Blocked6: 9

    stage:
      hardware:
        -
          name: ASI
          type: ASI
          serial_number: 123456789
          axes: [x, y, f]
          axes_mapping: [X, Y, Z]
          volts_per_micron: None
          axes_channels: None
          max: None
          min: None
        -
          name: GalvoNIStage
          type: GalvoNIStage
          serial_number: 987654321
          axes: [z]
          axes_mapping: [ PXI6723/ao1 ]
          volts_per_micron: 0.05*x
          max: 10
          min: -10
        -
          name: SyntheticStage
          type: SyntheticStage
          serial_number: 123
          axes: [theta]
          axes_mapping: [theta]
          max: 360
          min: 0
      joystick_axes: [x, y, z]
      x_max: 100000
      x_min: -100000
      y_max: 100000
      y_min: -100000
      z_max: 100000
      z_min: -100000
      f_max: 100000
      f_min: -100000
      theta_max: 360
      theta_min: 0
      x_step: 500
      y_step: 500
      z_step: 500
      theta_step: 30
      f_step: 500
      velocity: 1000

      x_offset: 0
      y_offset: 0
      z_offset: 0
      theta_offset: 0
      f_offset: 0

      flip_x: False
      flip_y: False
      flip_z: False

    zoom:
      hardware:
        name: zoom
        type: SyntheticZoom
        servo_id: 1
      position:
        0.63x: 0
        1x: 627
        2x: 1711
        3x: 2301
        4x: 2710
        5x: 3079
        6x: 3383
      pixel_size:
        0.63x: 9.7
        1x: 6.38
        2x: 3.14
        3x: 2.12
        4x: 1.609
        5x: 1.255
        6x: 1.044
      stage_positions:
        BABB:
          f:
            0.63x: 0
            1x: 1
            2x: 2
            3x: 3
            4x: 4
            5x: 5
            6x: 6

    shutter:
      hardware:
        name: daq
        type: SyntheticShutter #NI
        channel: PXI6723/port0/line0
        min: 0
        max: 5

    lasers:
      - wavelength: 405
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCI6321/port0/line3
            min: 0
            max: 5
        power: #analog
          hardware:
            name: daq
            type: SyntheticLaser
            channel: PCI6321/ao1
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87

      - wavelength: 488
        onoff: #digital
          hardware:
            name: daq
            type: NI
            channel: PCI6321/port0/line5
            min: 0
            max: 5
        power: #analog
          hardware:
            name: daq
            type: SyntheticLaser
            channel: PCI6321/ao0
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87

      - wavelength: 561
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCI6321/port0/line7
            min: 0
            max: 5
        power: #analog
          hardware:
            name: daq
            type: SyntheticLaser
            channel: PCI6321/ao1
            min: 0
            max: 5
        type: Obis
        index: 1
        delay_percent: 10
        pulse_percent: 87

      - wavelength: 640
        onoff: #digital
          hardware:
            name: daq
            type: NI
            channel: PCI6321/port0/line1
            min: 0
            max: 5
        power: #analog
          hardware:
            name: daq
            type: SyntheticLaser
            channel: PCI6321/ao2
            min: 0
            max: 5
        type: LuxX
        index: 2
        delay_percent: 10
        pulse_percent: 87

gui:
  channels:
    count: 5
    laser_power:
      min: 0
      max: 100
      step: 10
    exposure_time:
      min: 1
      max: 1000
      step: 5
    interval_time:
      min: 0
      max: 1000
      step: 5
  stack_acquisition:
    step_size:
      min: 0.100
      max: 1000
      step: 0.1
    start_pos:
      min: -5000
      max: 5000
      step: 1
    end_pos:
      min: -5000
      max: 10000
      step: 1
  timepoint:
    timepoints:
      min: 1
      max: 1000
      step: 1
    stack_pause:
      min: 0
      max: 1000
      step: 1
