%YAML 1.2
---

ETLConstants:
  high_resolution: {
    488nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
      offset: 0
    }
  }
  0.63x: {
    488nm: {
      amplitude: 2.336,
        offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
        offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
        offset: 0
    }
  }
  1x: {
    488nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
      offset: 0
    }
  }
  2x: {
    488nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
      offset: 0
    }
  }
  3x: {
    488nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
      offset: 0
    }
  }
  4x: {
    488nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
      offset: 0
    }
  }
  5x: {
    488nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
      offset: 0
    }
  }
  6x: {
    488nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    562nm: {
      amplitude: 2.336,
      offset: 0
    } ,
    642nm: {
      amplitude: 2.336,
      offset: 0
    }
  }
  