%YAML 1.2
---
User:
  name: Kevin_Dean

Saving:
  auto_save: False
  auto_save_waterfall: True
  root_directory: /Users/S155475/Desktop
  filename_video: Video # Can be the same filename for video and photo
  filename_photo: Snap
  filename_waterfall: Waterfall
  filename_trajectory: Trajectory
  filename_log: Log
  max_memory: 800 # In megabytes
  # These are filled by the GUI
  save_directory:
  user:
  tissue:
  celltype:
  label:
  date:

DAQParameters:
    hardware_type: NI

    # triggers
    master_trigger_out_line: PXI6259/port0/line1
    camera_trigger_out_line: /PXI6259/ctr0
    trigger_source: /PXI6259/PFI0

    # galvos
    galvo_left: ao0
    galvo_right: ao1

    # ETL
    etl_left: ao2
    etl_right: ao3

    # lasers
    number_of_lasers : 3
    laser_0_wavelength: 488nm
    laser_0: PXI6733/port0/line2

    laser_1_wavelength: 562nm
    laser_1: PXI6733/port0/line3

    laser_2_wavelength: 642nm
    laser_2: PXI6733/port0/line4

    # shutters
    shutter_left: PXI6259/port0/line0
    shutter_right: PXI6259/port2/line0

CameraParameters:
  type: SyntheticCamera #HamamatsuOrca or SyntheticCamera
  number_of_cameras: 2
  x_pixels: 2048
  y_pixels: 2048
  x_pixel_size_in_microns: 6.5
  y_pixel_size_in_microns: 6.5
  subsampling: [1, 2, 4]
  sensor_mode: 12  # 12 for progressive
  defect_correct_mode: 2
  binning: 1x1
  readout_speed: 1
  trigger_active: 1
  trigger_mode: 1 # it is unclear if this is the external lightsheeet mode - how to check this?
  trigger_polarity: 2  # positive pulse
  trigger_source: 2  # external
  camera_line_interval: 0.000075
  camera_exposure_time: 200 # in ms
  ASLM_from_volt: 0  # first voltage applied at remote mirror
  ASLM_to_volt: 1  # voltage applied at remote mirror at the end of sawtooth
  ASLM_current_volt: 0  # current voltage applied to remote mirror
  ASLM_static_low_res_volt: 0  # default ASLM low res voltage
  ASLM_static_high_res_volt: 0  # default ASLM high res voltage
  ASLM_alignment_on: 0  # param=1 if ASLM alignment mode is on, otherwise zero
  ASLM_delay_before_voltage_return: 0.001  # 1ms
  ASLM_additional_return_time: 0.001  # 1ms

ETLParameters:
  type: SyntheticETL
  number_of_etls: 2


StageParameters:
    stage_type: PI
    controllername: C-884
    stages: (L-509.20DG10, L-509.40DG10, L-509.20DG10, M-060.DG, M-406.4PD, NOSTAGE)
    refmode: (FRF, FRF, FRF, FRF, FRF, FRF,)
    serialnum: 119060508
    y_unload_position: 10000
    y_load_position: 90000
    startfocus: 70700
    x_max: 50000
    x_min: 2000
    y_max: 100000
    y_min: 2000
    z_max: 50000
    z_min: 2000
    f_max: 100000
    f_min: 2000
    theta_max: 360
    theta_min: 0
    x_rot_position: 2000
    y_rot_position: 2000
    z_rot_position: 2000

StartupParameters:
  state: init  # init, idle, live, snap, running_script
  samplerate: 100000
  sweeptime: 0.2
  position: {
    x_pos: 0,
    y_pos: 0,
    z_pos: 0,
    f_pos: 0,
    theta_pos: 0
  }
  ETL_cfg_file: C:/Users/Spectral/Documents/GitHub/multiscale_microscope/base/1.0.0/config/etl_parameters/ETL-parameters.csv
  file_prefix:
  file_suffix: 000001
  zoom: 1x
  pixelsize: 6.55
  laser: 488 nm
  max_laser_voltage: 10
  intensity: 10
  shutterstate: False  # Is the shutter open or not?
  shutterconfig: Left  # Can be "Left" "Right" "Both" "Interleaved"
  etl_l_delay_percent: 7.5
  etl_l_ramp_rising_percent: 85
  etl_l_ramp_falling_percent: 2.5
  etl_l_amplitude: 0.7
  etl_l_offset: 2.3
  etl_r_delay_percent: 2.5
  etl_r_ramp_rising_percent: 5
  etl_r_ramp_falling_percent: 85
  etl_r_amplitude: 0.65
  etl_r_offset: 2.36
  galvo_l_frequency: 99.9
  galvo_l_amplitude: 2.5
  galvo_l_offset: 0
  galvo_l_duty_cycle: 50
  galvo_l_phase: np.pi / 2
  galvo_r_frequency: 99.9
  galvo_r_amplitude: 2.5
  galvo_r_offset: 0
  galvo_r_duty_cycle: 50
  galvo_r_phase: np.pi / 2
  laser_l_delay_percent: 10
  laser_l_pulse_percent: 87
  laser_l_max_amplitude_percent: 100
  laser_r_delay_percent: 10
  laser_r_pulse_percent: 87
  laser_r_max_amplitude_percent: 100
  camera_delay_percent: 10
  camera_pulse_percent: 1
  camera_exposure_time: 0.01
  camera_line_interval: 0.000075
  camera_display_live_subsampling: 1
  camera_display_snap_subsampling: 1
  camera_display_acquisition_subsampling: 2
  camera_binning: 1x1
  camera_sensor_mode: ASLM
  average_frame_rate: 4.969



ZoomParameters:
    zoom_type: Dynamixel
    servo_id: 1
    COM_port: COM21
    baudrate: 1000000
    zoom_position: {
      0.63x: 0,
      1x: 627,
      2x: 1711,
      3x: 2301,
      4x: 2710,
      5x: 3079,
      6x: 3383
    }

    low_res_zoom_pixel_size: {
      0.63x: 9.7,
      1x: 6.38,
      2x: 3.14,
      3x: 2.12,
      4x: 1.609,
      5x: 1.255,
      6x: 1.044
    }

    high_res_zoom_pixel_size: 0.167

FilterWheelParameters:
    filter_wheel_type: Sutter
    filter_wheel_port: COM9
    number_of_filter_wheels: 2
    available_filters: {
      Empty-Alignment: 0,
      GFP - FF01-515/30-32: 1,
      RFP - FF01-595/31-32: 2,
      Far-Red - BLP01-647R/31-32: 3,
      Blocked1: 4,
      Blocked2: 5,
      Blocked3: 6,
      Blocked4: 7,
      Blocked5: 8,
      Blocked6: 9
    }

SharedMemoryAllocation:
  vol_per_buffer: 1
  num_data_buffers: 2  # increase for multiprocessing
  num_snap: 1  # interbuffer time limited by ao play
  images_per_buffer: 1
  bytes_per_data_buffer: images_per_buffer * 6000 * 4000 * 2
  bytes_per_preview_buffer: bytes_per_data_buffer * 3

MicroscopeState:
  image_mode: Continuous
  stack_cycling_mode: dummy_value
  save_data: 0
  timepoints: 1
  stack_pause: 0
  step_size: 1
