%YAML 1.2
---
User:
  name: Kevin_Dean

Saving:
  root_directory: E:\
  save_directory:
  user:
  tissue:
  celltype:
  label:
  date:

MicroscopeState:
  image_mode: continuous
  stack_cycling_mode: per_z
  start_position: 0
  end_position: 0
  step_size: 0
  number_z_steps: 0
  save_data: 0
  timepoints: 1
  stack_pause: 0
  step_size: 1
