{
  "Default": {
    "repeat": 1,
    "expand": 1,
  },
  "Confocal-Projection": {
    "repeat": timepoints,
    "expand": n_plane,
  },
  #Sriya : must specify this in the experiment.yml file
  #Sriya: waveform_template = 'Bidirectional':
  "Bidirectional": {
      "repeat": 1,
      "expand": 2,
  }
}