# Specify all necessary information to find and connect to each hardware
# device that will be used on any of the scopes.
hardware:
  daq:
    type: NI
  camera:
    -
      type:  HamamatsuOrcaLightning #SyntheticCamera
      serial_number: 000035
    -
      type: Photometrics
      camera_connection: PMPCIECam00
      serial_number: 1
  filter_wheel:
    type: ASI #SyntheticFilterWheel
    port: COM8
    baudrate: 115200
    number_of_wheels: 2
  stage:
    -
      type: ASI
      serial_number: 123456789
      port: COM8
      baudrate: 115200
    -
      type: SyntheticStage
      serial_number: 987654321
  zoom:
    type: SyntheticZoom
    servo_id: 0
    port: 0
    baudrate: 0

# Only one microscope can be active in the GUI at a time, but all microscopes will be accessible
microscopes:
  Nanoscale:
    daq:
      hardware:
        name: daq
        type: NI

      # NI PCIe-1073 Chassis with PXI-6259 and PXI-6733 DAQ Boards.
      # Sampling rate in Hz
      sample_rate: 100000
      sweep_time: 0.2

      # triggers
      master_trigger_out_line: PXI6259/port0/line1
      camera_trigger_out_line: /PXI6259/ctr0
      trigger_source: /PXI6259/PFI0

      # Digital Laser Outputs
      laser_port_switcher: PXI6733/port0/line1
      laser_switch_state: False

    camera:
      hardware:
        name: camera
        type: HamamatsuOrcaLightning #SyntheticCamera
        serial_number: 000035
      x_pixels: 4608.0
      y_pixels: 2592.0
      pixel_size_in_microns: 5.5
      subsampling: [1, 2, 4]
      sensor_mode: Normal  # 12 for progressive, 1 for normal.
      readout_direction: Bottom-to-Top  # Top-to-Bottom', 'Bottom-to-Top'
      lightsheet_rolling_shutter_width: 608
      defect_correct_mode: 2.0
      binning: 1x1
      readout_speed: 0x7FFFFFFF
      trigger_active: 1.0
      trigger_mode: 1.0 # external light-sheet mode
      trigger_polarity: 2.0  # positive pulse
      trigger_source: 2.0  # 2 = external, 3 = software.
      exposure_time: 20 # Use milliseconds throughout.
      delay_percent: 30 #30 #25 #8 #5.0
      pulse_percent: 1
      line_interval: 0.000075
      display_acquisition_subsampling: 4
      average_frame_rate: 4.969
      frames_to_average: 1
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
    remote_focus_device:
      hardware:
        name: daq
        type: NI
        channel: PXI6259/ao3
        min: -0.5
        max: 0.5
      # Optotune EL-16-40-TC-VIS-5D-1-C
      delay_percent: 0 #1.5 #7.5
      ramp_rising_percent: 85
      ramp_falling_percent: 1.5 #2.5
      amplitude: 0.7
      offset: 2.3
    galvo:
      -
        hardware:
          name: daq
          type: NI
          channel: PXI6259/ao1
          min: 0
          max: 5
        frequency: 99.9
        amplitude: 2.5
        offset: 0
        duty_cycle: 50
        phase: 1.57079 # pi/2
    filter_wheel:
      hardware:
        name: filter_wheel
        type: ASI #SyntheticFilterWheel
        wheel_number: 2
      filter_wheel_delay: .030 # in seconds
      available_filters:
        BLU - FF01-442/42-32: 0
        GFP - FF01-515/30-32: 1
        RFP - FF01-595/31-32: 2
        Far-Red - FF01-670/30-32: 3
        Blocked1: 4
        Empty: 5
        Blocked3: 6
        Blocked4: 7
        Blocked5: 8
        Blocked6: 9
    stage:
      hardware:
        -
          name: stage
          type: ASI
          serial_number: 123456789
          axes: [x, y, z, f] # Software
          axes_mapping: [M, Y, X, Z] # M Shear axis mapping
          #axes_mapping: [M, X, Y, Z] #testing y
          #axes_mapping: [M, X, Z, Y] #testing Z
          # axes_mapping: [Z, Y, X, M]
          feedback_alignment: [90, 90, 90, 90]

        -
          name: stage
          type: SyntheticStage
          serial_number: 987654321
          axes: [theta]

      startfocus: -16000
      x_max: 0 # Swapped from Z
      x_min: -22708.3 # Swapped from Z
      y_max: 1361.3
      y_min: -3496.3
      z_max: 3521.9 # Swapped from X
      z_min: -4551.1 # Swapped from X
      f_max: 3233.0 #=m
      f_min: -9382.0 #=m
      theta_max: 360
      theta_min: 0
      external_trigger: /PXI6259/PFI1
      # joystick_axes: [x, y, z, f]

      x_rot_position: 2000
      y_rot_position: 2000
      z_rot_position: 2000

      x_step: 50
      y_step: 50
      z_step: 50
      theta_step: 30
      f_step: 50

      position:
        x_pos: 5 # Swapped from Z initial stage position
        y_pos: 1
        z_pos: 1 # Swapped from X
        f_pos: 0
        theta_pos: 0
      velocity: 1000

      x_offset: 0
      y_offset: 0
      z_offset: 0
      f_offset: 0
      theta_offset: 0
    zoom:
      hardware:
        name: zoom
        type: SyntheticZoom
        servo_id: 1
      position:
        N/A: 0
      pixel_size:
        N/A: 0.168
    shutter:
      hardware:
        name: daq
        type: NI
        channel: PXI6259/port0/line0
        min: 0
        max: 5
    lasers:
      # Omicron LightHub Ultra
      # 488 and 640 are LuxX+ Lasers
      # 561 is a Coherent OBIS Laser
      # Digital Laser Outputs
      - wavelength: 405
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line2
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao0
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 488
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line3
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao1
            min: 0
            max: 5
        type: LuxX
        index: 1
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 561
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line4
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao2
            min: 0
            max: 5
        type: Obis
        index: 2
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 642
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line5
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao3
            min: 0
            max: 5
        type: LuxX
        index: 3
        delay_percent: 10
        pulse_percent: 87
      - wavelength: LED
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao4
            min: 0
            max: 5
        index: 4

  Macroscale:
    daq:
      hardware:
        name: daq
        type: NI

      # NI PCIe-1073 Chassis with PXI-6259 and PXI-6733 DAQ Boards.
      # Sampling rate in Hz
      sample_rate: 100000
      sweep_time: 0.2

      # triggers
      master_trigger_out_line: PXI6259/port0/line1
      camera_trigger_out_line: /PXI6259/ctr0
      trigger_source: /PXI6259/PFI0

      # Digital Laser Outputs
      laser_port_switcher: PXI6733/port0/line1
      laser_switch_state: True

    camera:
      hardware:
        name: camera
        type: Photometrics #SyntheticCamera
        serial_number: 1
      x_pixels: 5056.0
      y_pixels: 2960.0
      pixel_size_in_microns: 4.25
      subsampling: [1, 2, 4]
      sensor_mode: Normal  # 12 for progressive, 1 for normal.
      readout_direction: Bottom-to-Top  # Top-to-Bottom', 'Bottom-to-Top'
      lightsheet_rolling_shutter_width: 608
      defect_correct_mode: 2.0
      binning: 1x1
      readout_speed: 0x7FFFFFFF
      trigger_active: 1.0
      trigger_mode: 1.0 # external light-sheet mode
      trigger_polarity: 2.0  # positive pulse
      trigger_source: 2.0  # 2 = external, 3 = software.
      exposure_time: 20 # Use milliseconds throughout.
      delay_percent: 25 #8 #5.0
      pulse_percent: 1
      line_interval: 0.000075
      display_acquisition_subsampling: 4
      average_frame_rate: 4.969
      frames_to_average: 1
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
    remote_focus_device:
      hardware:
        name: daq
        type: NI
        channel: PXI6259/ao3
        min: -0.5
        max: 0.5
      # Optotune EL-16-40-TC-VIS-5D-1-C
      delay_percent: 0 #1.5 #7.5
      ramp_rising_percent: 85
      ramp_falling_percent: 2.5
      amplitude: 0.7
      offset: 2.3
    galvo:
      -
        hardware:
          name: daq
          type: NI
          channel: PXI6259/ao1
          min: 0
          max: 5
        frequency: 99.9
        amplitude: 2.5
        offset: 0
        duty_cycle: 50
        phase: 1.57079 # pi/2
    filter_wheel:
      hardware:
        name: filter_wheel
        type: ASI #SyntheticFilterWheel
        wheel_number: 2
      filter_wheel_delay: .030 # in seconds
      available_filters:
        BLU - FF01-442/42-32: 0
        GFP - FF01-515/30-32: 1
        RFP - FF01-595/31-32: 2
        Far-Red - FF01-670/30-32: 3
        Blocked1: 4
        Empty: 5
        Blocked3: 6
        Blocked4: 7
        Blocked5: 8
        Blocked6: 9
    stage:
      hardware:
        -
          name: stage
          type: ASI
          serial_number: 123456789
          axes: [x, y, z, f] #Software
          # axes_mapping: [M, Y, X, Z]
          axes_mapping: [M, Y, X, Z] #M  shear
          feedback_alignment: [90, 90, 90, 90]

        -
          name: stage
          type: SyntheticStage
          serial_number: 987654321
          axes: [theta]

      startfocus: -16000
      x_max: 0 # Swapped from Z
      x_min: -22708.3 # Swapped from Z
      y_max: 1361.3
      y_min: -3496.3
      z_max: 3521.9 # Swapped from X
      z_min: -4651.1 # Swapped from X
      f_max: 3233.0 #=m
      f_min: -9382.0 #=m
      theta_max: 360
      theta_min: 0
      external_trigger: /PXI6259/PFI1
      # joystick_axes: [x, y, z, f]

      x_rot_position: 2000
      y_rot_position: 2000
      z_rot_position: 2000

      x_step: 50
      y_step: 50
      z_step: 50
      theta_step: 30
      f_step: 50

      position:
        x_pos: 5 # Swapped from Z initial stage position
        y_pos: 1
        z_pos: 1 # Swapped from X
        f_pos: 0
        theta_pos: 0
      velocity: 1000

      x_offset: 0
      y_offset: 0
      z_offset: 0
      f_offset: 0
      theta_offset: 0
    zoom:
      hardware:
        name: zoom
        type: SyntheticZoom
        servo_id: 1
      position:
        N/A: 0
      pixel_size:
        N/A: 1.06
    shutter:
      hardware:
        name: daq
        type: NI
        channel: PXI6259/port0/line0
        min: 0
        max: 5
    lasers:
      # Omicron LightHub Ultra
      # 488 and 640 are LuxX+ Lasers
      # 561 is a Coherent OBIS Laser
      # Digital Laser Outputs
      - wavelength: 405
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line2
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao0
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 488
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line3
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao1
            min: 0
            max: 5
        type: LuxX
        index: 1
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 561
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line4
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao2
            min: 0
            max: 5
        type: Obis
        index: 2
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 642
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/port0/line5
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao3
            min: 0
            max: 5
        type: LuxX
        index: 3
        delay_percent: 10
        pulse_percent: 87
      - wavelength: LED
        power:
          hardware:
            name: daq
            type: NI
            channel: PXI6733/ao4
            min: 0
            max: 5
        index: 4


gui:
  channels:
    count: 5
    laser_power:
      min: 0
      max: 100
      step: 10
    exposure_time:
      min: 1
      max: 1000
      step: 5
    interval_time:
      min: 0
      max: 1000
      step: 5
  stack_acquisition:
    step_size:
      min: 0.1
      max: 1000
      step: 0.1
    start_pos:
      min: -5000
      max: 5000
      step: 1
    end_pos:
      min: -5000
      max: 10000
      step: 1
  timepoint:
    timepoints:
      min: 1
      max: 1000
      step: 1
    stack_pause:
      min: 0
      max: 1000
      step: 1
