# Specify all necessary information to find and connect to each hardware
# device that will be used on any of the scopes.
hardware:
  daq:
    type: NI
  camera:
    -
      type: HamamatsuOrca # HamamatsuOrca
      serial_number: 003209
  filter_wheel:
    type: ASI #SyntheticFilterWheel #SutterFilterWheel
    port: COM8
    baudrate: 115200
    number_of_wheels: 1
  stage:
    -
      type: ASI
      port: COM8
      timeout: 0.25
      baudrate: 115200
      serial_number: 0000
      stages: None
  zoom:
    type: SyntheticZoom
    servo_id: 1
    port: COM18
    baudrate: 1000000

# Only one microscope can be active in the GUI at a time, but all microscopes will be accessible
microscopes:
  BTMesoSPIM:
    daq:
      hardware:
        name: daq
        type: NI
      sample_rate: 100000
      sweep_time: 0.2

      # triggers
      master_trigger_out_line: PCI6738/port0/line1 #3
      camera_trigger_out_line: /PCI6738/ctr0 #9/42
      trigger_source: /PCI6738/PFI0 #4

      # Digital Laser Outputs
      laser_port_switcher: PCI6738/port0/line0
      laser_switch_state: False

    camera:
      hardware:
        name: camera
        type: HamamatsuOrca
        serial_number: 003209
      x_pixels: 2048.0
      y_pixels: 2048.0
      pixel_size_in_microns: 6.5
      subsampling: [1, 2, 4]
      sensor_mode: Normal  # 12 for progressive, 1 for normal. Normal/Light-Sheet
      readout_direction: Top-to-Bottom  # Top-to-Bottom', 'Bottom-to-Top'
      lightsheet_rolling_shutter_width: 608
      defect_correct_mode: 1.0 #2.0
      binning: 1x1
      readout_speed: 2.0
      trigger_active: 1.0
      trigger_mode: 1.0 # external light-sheet mode
      trigger_polarity: 2.0  # positive pulse
      trigger_source: 2.0  # 2 = external, 3 = software.
      exposure_time: 20 # Use milliseconds throughout.
      delay_percent: 10
      pulse_percent: 1
      line_interval: 0.000075
      display_acquisition_subsampling: 4
      average_frame_rate: 4.969
      frames_to_average: 1
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
      flip_x: True
      flip_y: False
    remote_focus_device:
      hardware:
        name: remote_focus
        type: NI # SyntheticRemoteFocus #EquipmentSolutions # NI
        channel: PCI6738/ao2  #45/46
        comport: COM7
        min: 0
        max: 5
      delay_percent: 7.5
      ramp_rising_percent: 85
      ramp_falling_percent: 2.5
      amplitude: 0.7
      offset: 2.3
      smoothing: 0.0
    galvo:
      -
        hardware:
          name: daq # digitally scanned galvo
          type: NI
          channel: PCI6738/ao0  #10/11
          min: -5
          max: 5
        waveform: sawtooth
        frequency: 99.9
        amplitude: 2.5
        offset: 0.5
        duty_cycle: 50
        phase: 1.57079 # pi/2

    filter_wheel:
      hardware:
        name: filter_wheel
        type: ASI #SyntheticFilterWheel #SutterFilterWheel
        wheel_number: 1
      filter_wheel_delay: .030 # in seconds
      available_filters:
        525-30: 0
        600-37: 1
        647LP: 2
        Empty1: 3
        Empty2: 4
        670-30: 5
        Blocked2: 6
        Empty3: 7
        Blocked3: 8
        Blocked4: 9
    stage:
      hardware:
        -
          name: stage
          type: ASI
          serial_number: 0000
          axes: [x, y, z, f, theta]
          feedback_alignment: [88, 91, 91, 91, 85]
          axes_mapping: [X, V, Z, Y, T]
          volts_per_micron: None
          axes_channels: None
          max: 5
          min: 0

      joystick_axes: [x, y, z, theta, f]
      x_max: 125000
      x_min: -125000
      y_max: 125000
      y_min: -125000
      z_max: 50000
      z_min: -50000
      f_max: 1000000
      f_min: -1000000
      theta_max: 360000
      theta_min: -360000

      flip_x: False
      flip_y: False
      flip_z: False

      x_step: 500
      y_step: 500
      z_step: 50
      theta_step: 30
      f_step: 500
      velocity: 1000

      x_offset: 0
      y_offset: 0
      z_offset: 0
      theta_offset: 0
      f_offset: 0
    zoom:
      hardware:
        name: zoom
        type: SyntheticZoom
        servo_id: 1
      position:
        5X: 0
        4X: 0
      pixel_size:
        5X: 1.2  # 1.2 in BABB
        4X: 1.3  # 1.3 in BABB
      stage_positions:
        BABB:
          f:
            5X: 0
            4X: 0
    shutter:
      hardware:
        name: daq
        type: SyntheticShutter
        channel: PCI6738/port0/line10
        min: 0
        max: 5
    lasers:
      - wavelength: 488
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCI6738/port1/line5 # 7/41
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCI6738/ao8 # 1  # 44/11
            min: 0
            max: 5
        type: Obis
        index: 0
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 561
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCI6738/port1/line2 # 5/39
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCI6738/ao9 # 3  # 12/46
            min: 0
            max: 5
        type: Obis
        index: 1
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 638
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCI6738/port1/line3 # 6/39
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCI6738/ao10 # 4  # 13/14
            min: 0
            max: 5
        type: Obis
        index: 2
        delay_percent: 10
        pulse_percent: 87

gui:
  channels:
    count: 5
    laser_power:
      min: 0
      max: 100
      step: 10
    exposure_time:
      min: 1
      max: 1000
      step: 5
    interval_time:
      min: 0
      max: 1000
      step: 5
  stack_acquisition:
    step_size:
      min: 0.100
      max: 1000
      step: 0.1
    start_pos:
      min: -5000
      max: 5000
      step: 1
    end_pos:
      min: -5000
      max: 10000
      step: 1
  timepoint:
    timepoints:
      min: 1
      max: 1000
      step: 1
    stack_pause:
      min: 0
      max: 1000
      step: 1


# BDVParameters:
# # The following parameters are used to configure the BigDataViewer
#   # visualization. See the BigDataViewer documentation for more details.
#   # https://imagej.net/BigDataViewer
#   shear:
#     shear_data: True
#     shear_dimension: YZ # XZ, YZ, or XY
#     shear_angle: 45
#   rotate:
#     rotate_data: False
#     rotate_dimension: X # X, Y, Z
#     rotate_angle: 0
