name: deploy

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  deploy:
      # this will run when you have tagged a commit, starting with "v*"
      # and requires that you have put your twine API key in your
      # github secrets (see readme for details)
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          python-version: ["3.9"]
          operating-system: [windows-latest]
      if: contains(github.ref, 'tags')
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.9" #"3.x"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -U setuptools build twine
        - name: Build and publish
          env:
            TWINE_USERNAME: kdean #__token__
            TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
          run: |
            git tag
            python -m build
            twine upload dist/*
